#!/bin/sh

apt install zsh

wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O - | zsh

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

chsh -s `which zsh`
